version: '3.8'

services:
  eshopping-api:
    build:
      context: ./path_to_eshopping_api_directory
      dockerfile: Dockerfile
    image: eshopping-api:latest
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__MongoDB=mongodb://mongo:27017
      - MongoDatabaseName=ProductDb
      - ConnectionStrings__CollectionName=Products
      - ConnectionStrings__BrandsCollection=ProductBrands
      - ConnectionStrings__TypesCollection=ProductTypes
    depends_on:
      - mongo

  basket-api:
    build:
      context: ./path_to_basket_api_directory
      dockerfile: Dockerfile
    image: basket-api:latest
    ports:
      - "5001:80"
    environment:
      - CacheSettings__ConnectionString=redis:6379,password=Ali1234567,abortConnect=false
    depends_on:
      - redis

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
      - "8000:8000" # For the agent communication
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  mongo:
    image: mongo:5.0.3-focal
    environment:
      MONGO_INITDB_DATABASE: ProductDb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  redis:
    image: redis:alpine
    container_name: redis
    command: ["redis-server", "--requirepass", "Ali1234567"]
    ports:
      - "6379:6379"
    restart: always

volumes:
  mongo-data:
  redis-data:
  portainer_data: {}