version: '3.8'

services:
  eshopping-api:
    image: eshopping-api:latest
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__MongoDB=mongodb://mongo:27017
      - MongoDatabaseName=ProductDb
      - ConnectionStrings__CollectionName=Products
      - ConnectionStrings__BrandsCollection=ProductBrands
      - ConnectionStrings__TypesCollection=ProductTypes
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ProductDb
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
