version: '3.8'

services:
  eshopping-api:
    build:
      context: ./Catalog.Api
    image: eshopping-api:latest
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__MongoDB=mongodb://mongo:27017
      - MongoDatabaseName=ProductDb
      - ConnectionStrings__CollectionName=Products
      - ConnectionStrings__BrandsCollection=ProductBrands
      - ConnectionStrings__TypesCollection=ProductTypes
    depends_on:
      - mongo

  basket-api:
    build:
      context: ./Basket.Api 
    image: basket-api:latest
    ports:
      - "5001:80"
    environment:
      - CacheSettings__ConnectionString=redis:6379,password=Ali1234567,abortConnect=false
    depends_on:
      - redis

  discount-api:
     build:
      context: ./Discount.Api
     image: discount-api:latest
     environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=Password@1;"          
     depends_on:
      - discountdb
     ports:
      - "5002:80"

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
      - "8000:8000" # For the agent communication
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  mongo:
    image: mongo:5.0.3-focal
    environment:
      - MONGO_INITDB_DATABASE=ProductDb # No spaces around the equals sign

    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  redis:
    image: redis:alpine
    container_name: redis
    command: ["redis-server", "--requirepass", "Ali1234567"]
    ports:
      - "6379:6379"
    restart: always

  discountdb:
    image: postgres:alpine
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Password@1
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@eShopping.net
      - PGADMIN_DEFAULT_PASSWORD=Password@1
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

volumes:
  mongo-data:
  redis-data:
  portainer_data: {}
  postgres_data:
  pgadmin_data: