//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basket.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Basket.Common.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهت فعالسازی حساب کاربری خود رو لینک زیر کلیک کنید.
        /// </summary>
        public static string ActivateAccount {
            get {
                return ResourceManager.GetString("ActivateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعالسازی حساب کاربری.
        /// </summary>
        public static string ActivateAccountSubject {
            get {
                return ResourceManager.GetString("ActivateAccountSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آگهی ای با این نام موجود است.
        /// </summary>
        public static string AdExists {
            get {
                return ResourceManager.GetString("AdExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آگهی ای یافت نشد.
        /// </summary>
        public static string AdveriseNotFound {
            get {
                return ResourceManager.GetString("AdveriseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای بازدید از این ملک چنین روزی تعیین نشده است .
        /// </summary>
        public static string AdvertiseDayNotMatch {
            get {
                return ResourceManager.GetString("AdvertiseDayNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سن نباید کمتر از 18 باشد.
        /// </summary>
        public static string AgeError {
            get {
                return ResourceManager.GetString("AgeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن همراه ،ایمیل و یا نام کاربری تکراریست!.
        /// </summary>
        public static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن همراه ، نام کاربری ،ایمیل و یا کد املاک تکراریست!.
        /// </summary>
        public static string AlreadyExists2 {
            get {
                return ResourceManager.GetString("AlreadyExists2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receivers.
        /// </summary>
        public static string CacheKeyOfReceivers {
            get {
                return ResourceManager.GetString("CacheKeyOfReceivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید درخواست بازدید از ملک.
        /// </summary>
        public static string ConfirmVisit {
            get {
                return ResourceManager.GetString("ConfirmVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشکلی در ثبت به وجود آمده است!!.
        /// </summary>
        public static string CreateError {
            get {
                return ResourceManager.GetString("CreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این روز برای آگهی شما ثبت شده است.
        /// </summary>
        public static string DaysExists {
            get {
                return ResourceManager.GetString("DaysExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشکلی در حذف به وجود آمده است!!.
        /// </summary>
        public static string DeleteError {
            get {
                return ResourceManager.GetString("DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رکوردی برای نمایش وجود ندارد.
        /// </summary>
        public static string EmailRecordNull {
            get {
                return ResourceManager.GetString("EmailRecordNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل های اطلاع رسانی ارسال شدند.
        /// </summary>
        public static string EmailsSent {
            get {
                return ResourceManager.GetString("EmailsSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست بازدید شما از ملک آگهی شده.
        /// </summary>
        public static string EmailSubject1 {
            get {
                return ResourceManager.GetString("EmailSubject1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مورد تایید قرار گرفت.
        /// </summary>
        public static string EmailSubject1_1 {
            get {
                return ResourceManager.GetString("EmailSubject1-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست بازدید از ملک آگهی شده شما، توسط .
        /// </summary>
        public static string EmailSubject2 {
            get {
                return ResourceManager.GetString("EmailSubject2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای شما ارسال شده است.
        /// </summary>
        public static string EmailSubject2_1 {
            get {
                return ResourceManager.GetString("EmailSubject2-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پارامترهای ارسالی را کامل و صحیح وارد کنید..
        /// </summary>
        public static string EnterParametersCorrectlyAndCompletely {
            get {
                return ResourceManager.GetString("EnterParametersCorrectlyAndCompletely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات املاک نمیتواند خالی باشد.
        /// </summary>
        public static string EstateInfo {
            get {
                return ResourceManager.GetString("EstateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدت زمان در نظر گرفته شده منقضی شده است.
        /// </summary>
        public static string ExpiredDate {
            get {
                return ResourceManager.GetString("ExpiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهت بازیابی رمزعبور کد ذیل را در فیلد مربوطه وارد کنید.دقت شود که این کد تا 5 دقیقه معتبر است.
        /// </summary>
        public static string ForgotPassword1 {
            get {
                return ResourceManager.GetString("ForgotPassword1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا مجددا تلاش کنید.
        /// </summary>
        public static string GeneralErrorTryAgain {
            get {
                return ResourceManager.GetString("GeneralErrorTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عکس وارد شود.
        /// </summary>
        public static string ImageRequired {
            get {
                return ResourceManager.GetString("ImageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The response has already started, the http status code middleware will not be executed..
        /// </summary>
        public static string InvalidOperationException {
            get {
                return ResourceManager.GetString("InvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری شما فعال شده است.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکراری میباشد.
        /// </summary>
        public static string IsExists {
            get {
                return ResourceManager.GetString("IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارور در Mapping رخ داده است.
        /// </summary>
        public static string MapingError {
            get {
                return ResourceManager.GetString("MapingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرسنلی برای ارسال ایمیل وجود ندارد.
        /// </summary>
        public static string NewsReceiverError {
            get {
                return ResourceManager.GetString("NewsReceiverError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یافت نشد.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد مربوطه نباید خالی باشد.
        /// </summary>
        public static string NullField {
            get {
                return ResourceManager.GetString("NullField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور قبلی نادرست است.
        /// </summary>
        public static string PasswordDoesntMatch {
            get {
                return ResourceManager.GetString("PasswordDoesntMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور نباید کمتر از 8 حرف باشد.
        /// </summary>
        public static string PasswordMin {
            get {
                return ResourceManager.GetString("PasswordMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمزعبور باید شامل اعداد ، حروف کوچک و بزرگ و حروف خاص باشد.
        /// </summary>
        public static string PasswordQuality {
            get {
                return ResourceManager.GetString("PasswordQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمزعبور باید شامل حروف خاص باشد.
        /// </summary>
        public static string PasswordUnique {
            get {
                return ResourceManager.GetString("PasswordUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازیابی رمز عبور.
        /// </summary>
        public static string RecoveryPassword {
            get {
                return ResourceManager.GetString("RecoveryPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما قبلا درخواستی برای بازدید از این ملک ارسال کرده اید.
        /// </summary>
        public static string RequestExists {
            get {
                return ResourceManager.GetString("RequestExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست بازدید از ملک.
        /// </summary>
        public static string RequestVisit {
            get {
                return ResourceManager.GetString("RequestVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چنین دسترسی ای برای شما تعریف نشده است.
        /// </summary>
        public static string RoleDoesNotMatchUser {
            get {
                return ResourceManager.GetString("RoleDoesNotMatchUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش وارد شده تکراری میباشد.
        /// </summary>
        public static string RoleExist {
            get {
                return ResourceManager.GetString("RoleExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقشی یافت نشد.
        /// </summary>
        public static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توکن امنیتی منقضی شده است.
        /// </summary>
        public static string SecurityTokenExpiredException {
            get {
                return ResourceManager.GetString("SecurityTokenExpiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به دلیل نقض محدودیت کلید خارجی امکان درج یا آپدیت وجود ندارد.
        /// </summary>
        public static string SqlForeignKeyException {
            get {
                return ResourceManager.GetString("SqlForeignKeyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به دلیل نقض یونیک بودن بعضی از فیلدها امکان اضافه شدن و یا اپدیت وجود ندارد.
        /// </summary>
        public static string SqlUpdateException {
            get {
                return ResourceManager.GetString("SqlUpdateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی به این بخش بدون احراز هویت امکان پذیر نیست.
        /// </summary>
        public static string UnauthorizedAccessException {
            get {
                return ResourceManager.GetString("UnauthorizedAccessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشکلی در بروزرسانی به وجود آمده است!!.
        /// </summary>
        public static string UpdateError {
            get {
                return ResourceManager.GetString("UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری شما فعال نیست.
        /// </summary>
        public static string UserIsNotActive {
            get {
                return ResourceManager.GetString("UserIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد کننده آگهی نمیتواند برای آگهی خود درخواست بازدید بفرستد.
        /// </summary>
        public static string UserRequestError {
            get {
                return ResourceManager.GetString("UserRequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این نقش قبلا به این کاربر نسبت داده شده است.
        /// </summary>
        public static string UserRoleExist {
            get {
                return ResourceManager.GetString("UserRoleExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چنین آگهی ای برای این شخص تعریف نشده است.
        /// </summary>
        public static string WrongAdvertise {
            get {
                return ResourceManager.GetString("WrongAdvertise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روز های هفته باید شامل شنبه تا جمعه باشند.
        /// </summary>
        public static string WrongDaySelected {
            get {
                return ResourceManager.GetString("WrongDaySelected", resourceCulture);
            }
        }
    }
}
